# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtailmarkdown


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtailmarkdown.fields.MarkdownField(help_text='Use *emphasised* or **strong** text, link to <:Another page> or include <:image:An image.jpeg>.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
