# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 21:33
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
